deploy: true
folder_id: 178656066119
policy_boolean:
  constraints/iam.disableServiceAccountKeyCreation: true
  constraints/iam.NoServiceAccountExternalKeyCreation: true
  constraints/iam.disableServiceAccountKeyUpload: false
policy_list:
  constraints/iam.allowedPolicyMemberDomains:
    inherit_from_parent: false
    suggested_value: ""
    status: true
    values:
      - "southwire.com"