# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_version = ">= 1.6.2"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = ">= 5.20.0, <= 6.32.0"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = ">= 5.20.0, <= 6.32.0"
    }
  }
}

provider "google" {

  project = "melodic-furnace-403022"
  region  = "us-east4"
  zone    = "us-east4-a"
  default_labels = {
    cost-center   = "3385",
    provisioner   = "terraform",
    compliance    = "corporate",
    sensitivity   = "restricted",
    control-level = "info",
    lifecycle     = "prod"
  }
}
provider "google-beta" {
  project = "melodic-furnace-403022"
  region  = "us-east4"
  zone    = "us-east4-a"
  default_labels = {
    cost-center   = "3385",
    provisioner   = "terraform",
    compliance    = "corporate",
    sensitivity   = "restricted",
    control-level = "info",
    lifecycle     = "prod"
  }
}
