name: Terragrunt Action Workflow Prod

on:
 workflow_dispatch:
 push:
  branches:
  - main

jobs:
 terragrunt-job:
    uses: ../gh-actions-library/.github/workflows/terragrunt-gcp-prod.yml
    # uses: southwire/gh-actions-library/.github/workflows/terragrunt-gcp-prod.yml@main
    with:
      workingDirectory: folders
      environment: prod
      tfLog: 'ERROR'
